# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-520246a8-00f3-4210-b68c-b5027f84e865";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-520246a8-00f3-4210-b68c-b5027f84e865".device = "/dev/disk/by-uuid/520246a8-00f3-4210-b68c-b5027f84e865";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A2DE-A384";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-59394f29-6636-4dcf-8ee8-69b42ed9cb99"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
