$primary = rgb({{colors.primary.default.hex_stripped}})
$text    = rgb({{colors.on_surface.default.hex_stripped}})
$subtext = rgb({{colors.on_surface_variant.default.hex_stripped}})
$outline = rgb({{colors.outline_variant.default.hex_stripped}})
$field   = rgba({{colors.surface_container.default.hex_stripped}}cc)
$error   = rgb({{colors.error.default.hex_stripped}})
