<<<<<<< HEAD
$primary = rgb(e4b7f3)
$text    = rgb(e9e0e7)
$subtext = rgb(cec3cd)
$outline = rgb(4c444d)
$field   = rgba(231e23cc)
=======
$primary = rgb(dabaf9)
$text    = rgb(e8e0e8)
$subtext = rgb(ccc4ce)
$outline = rgb(4a454e)
$field   = rgba(221e24cc)
>>>>>>> laptop
$error   = rgb(ffb4ab)
