-- Generated by matugen. Don't edit; change the template instead.
local primary = "rgb(ffffff)"
local muted = "rgb(474747)"
local secondary = "rgb(c6c6c6)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = muted,
		},
	},
	group = {
		col = {
			border_active = primary,
			border_inactive = muted,
			border_locked_active = secondary,
			border_locked_inactive = muted,
		},
		groupbar = {
			col = {
				active = primary,
				inactive = muted,
				locked_active = secondary,
				locked_inactive = muted,
			},
		},
	},
})
