-- Generated by matugen. Don't edit; change the template instead.
local primary = "rgb(aec6ff)"
local muted = "rgb(44474f)"
local tertiary = "rgb(debcdf)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = muted,
		},
	},
	group = {
		col = {
			border_active = primary,
			border_inactive = muted,
			border_locked_active = tertiary,
			border_locked_inactive = muted,
		},
		groupbar = {
			col = {
				active = primary,
				inactive = muted,
				locked_active = tertiary,
				locked_inactive = muted,
			},
		},
	},
})
