-- Generated by matugen; base16 palette for mini.base16.
-- Only roles that stay readable on the background in every scheme
-- (the "fixed" roles go dark in the monochrome scheme).
return {
	base00 = "#191113", -- background
	base01 = "#261d1f", -- statusline, popups
	base02 = "#3c3234", -- selection
	base03 = "#9e8c8f", -- comments
	base04 = "#d6c2c5", -- dim text
	base05 = "#efdee0", -- text
	base06 = "#efdee0",
	base07 = "#efdee0",
	base08 = "#ffb4ab", -- errors, variables
	base09 = "#edbe92", -- numbers, constants
	base0A = "#e4bdc4", -- types, search
	base0B = "#edbe92", -- strings
	base0C = "#e4bdc4", -- escapes, regex
	base0D = "#ffb1c3", -- functions
	base0E = "#ffb1c3", -- keywords
	base0F = "#d6c2c5", -- braces, semicolons
}
