-- Generated by matugen; base16 palette for mini.base16.
-- Only roles that stay readable on the background in every scheme
-- (the "fixed" roles go dark in the monochrome scheme).
return {
	base00 = "#181115", -- background
	base01 = "#251e21", -- statusline, popups
	base02 = "#3b3236", -- selection
	base03 = "#9c8d93", -- comments
	base04 = "#d3c2c9", -- dim text
	base05 = "#eddfe4", -- text
	base06 = "#eddfe4",
	base07 = "#eddfe4",
	base08 = "#ffb4ab", -- errors, variables
	base09 = "#f3ba9d", -- numbers, constants
	base0A = "#dfbecd", -- types, search
	base0B = "#f3ba9d", -- strings
	base0C = "#dfbecd", -- escapes, regex
	base0D = "#fab1d9", -- functions
	base0E = "#fab1d9", -- keywords
	base0F = "#d3c2c9", -- braces, semicolons
}
