-- Generated by matugen. Don't edit; change the template instead.
local primary = "rgb({{colors.primary.default.hex_stripped}})"
local muted = "rgb({{colors.outline_variant.default.hex_stripped}})"
local secondary = "rgb({{colors.secondary.default.hex_stripped}})"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = muted,
		},
	},
	group = {
		col = {
			border_active = primary,
			border_inactive = muted,
			border_locked_active = secondary,
			border_locked_inactive = muted,
		},
		groupbar = {
			col = {
				active = primary,
				inactive = muted,
				locked_active = secondary,
				locked_inactive = muted,
			},
		},
	},
})
