-- Generated by matugen; base16 palette for mini.base16.
-- Only roles that stay readable on the background in every scheme
-- (the "fixed" roles go dark in the monochrome scheme).
return {
	base00 = "{{colors.surface.default.hex}}", -- background
	base01 = "{{colors.surface_container.default.hex}}", -- statusline, popups
	base02 = "{{colors.surface_container_highest.default.hex}}", -- selection
	base03 = "{{colors.outline.default.hex}}", -- comments
	base04 = "{{colors.on_surface_variant.default.hex}}", -- dim text
	base05 = "{{colors.on_surface.default.hex}}", -- text
	base06 = "{{colors.on_surface.default.hex}}",
	base07 = "{{colors.on_surface.default.hex}}",
	base08 = "{{colors.error.default.hex}}", -- errors, variables
	base09 = "{{colors.tertiary.default.hex}}", -- numbers, constants
	base0A = "{{colors.secondary.default.hex}}", -- types, search
	base0B = "{{colors.tertiary.default.hex}}", -- strings
	base0C = "{{colors.secondary.default.hex}}", -- escapes, regex
	base0D = "{{colors.primary.default.hex}}", -- functions
	base0E = "{{colors.primary.default.hex}}", -- keywords
	base0F = "{{colors.on_surface_variant.default.hex}}", -- braces, semicolons
}
