-- Monitors
MONITOR1 = "DP-1"
MONITOR2 = "HDMI-A-1"
MONITOR3 = ""
PRIMARY_MONITOR = MONITOR1

TERMINAL = "alacritty"
FILE_MANAGER = "dolphin"
EDITOR = "nvim"
CALCULATOR = "G"
BROWSER = "firefox"

NUM_WPM = 6
